# Generated by Django 5.1.1 on 2024-09-17 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_decription_orenjientry_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orenjientry',
            old_name='name',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='orenjientry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
